import {
  space,
  type FloorPlanInventoryEntry,
  type PlanPoint,
  type StackedFloorPlan,
} from './core';

const florenceDuomo: StackedFloorPlan = {
  mode: 'stacked-floorplan',
  floors: [
    {
      id: 'piazza',
      label: '广场与教堂基座',
      elevation: 0,
      stackOrder: 0,
      outline: [
        [-5, -8],
        [5, -8],
        [5, -3],
        [8, -3],
        [8, 3],
        [5, 3],
        [5, 8],
        [-5, 8],
        [-5, 3],
        [-8, 3],
        [-8, -3],
        [-5, -3],
        [-5, -8],
      ],
      spaces: [
        space('west-facade', '西立面观察区', 0, 7, 7.5, 1.4, 'outdoor'),
        space('drum-side', '侧墙与八角鼓座观察区', 6.4, 0, 2.2, 4.8, 'outdoor'),
        space(
          'ticket-entry',
          '票面指定登顶入口',
          -4,
          4.1,
          1.6,
          2,
          'circulation',
        ),
      ],
    },
    {
      id: 'inner-rim',
      label: '穹顶内缘与双壳通道',
      elevation: 3.6,
      stackOrder: 1,
      outline: [
        [-4, -4],
        [4, -4],
        [4, 4],
        [-4, 4],
        [-4, -4],
      ],
      spaces: [
        space(
          'shell-stair',
          '双壳之间登顶楼梯',
          -2.3,
          0,
          1.8,
          6.3,
          'circulation',
        ),
        space(
          'judgement-rim',
          '《最后的审判》内缘平台',
          1.2,
          0,
          3.6,
          6.3,
          'hall',
        ),
      ],
    },
    {
      id: 'lantern-terrace',
      label: '灯亭下方顶部露台',
      elevation: 7.2,
      stackOrder: 2,
      outline: [
        [-3.8, -3.8],
        [3.8, -3.8],
        [3.8, 3.8],
        [-3.8, 3.8],
        [-3.8, -3.8],
      ],
      spaces: [
        space('summit-terrace', '穹顶顶部露台', 0, 0, 6.8, 6.8, 'outdoor'),
      ],
    },
  ],
  openings: [
    {
      floorId: 'piazza',
      kind: 'gate',
      position: [-4, 5.4],
      connects: ['ticket-entry'],
    },
    {
      floorId: 'inner-rim',
      kind: 'archway',
      position: [-1.2, 0],
      connects: ['shell-stair', 'judgement-rim'],
    },
  ],
  routeStops: [
    { floorId: 'piazza', spaceId: 'west-facade', position: [0, 7] },
    { floorId: 'piazza', spaceId: 'drum-side', position: [6.4, 0] },
    { floorId: 'piazza', spaceId: 'ticket-entry', position: [-4, 4.1] },
    { floorId: 'inner-rim', spaceId: 'judgement-rim', position: [1.2, 0] },
    { floorId: 'lantern-terrace', spaceId: 'summit-terrace', position: [0, 0] },
  ],
  sourceManifest: [
    {
      authority: 'official',
      scope: ['footprint', 'spaces', 'levels'],
      title: 'Opera del Duomo: Cathedral and Brunelleschi dome architecture',
      url: 'https://duomo.firenze.it/en/discover/cathedral',
      verifiedAt: '2026-09-03',
    },
    {
      authority: 'official',
      scope: ['levels', 'route'],
      title: 'Opera del Duomo: Brunelleschi Pass visitor route',
      url: 'https://duomo.firenze.it/en/720/brunelleschi-pass',
      verifiedAt: '2026-09-03',
    },
  ],
  verticalLinks: [
    {
      id: 'dome-ascent',
      kind: 'stairs',
      label: '463级穹顶登顶楼梯',
      landings: [
        { floorId: 'piazza', position: [-4, 4.1] },
        { floorId: 'inner-rim', position: [-2.3, 2.4] },
      ],
    },
    {
      id: 'upper-shell-stair',
      kind: 'stairs',
      label: '双壳通道至顶部露台',
      landings: [
        { floorId: 'inner-rim', position: [-2.3, -2.4] },
        { floorId: 'lantern-terrace', position: [-2.3, -2.4] },
      ],
    },
  ],
};

const accademiaFlorence: StackedFloorPlan = {
  mode: 'stacked-floorplan',
  floors: [
    {
      id: 'ground',
      label: '地面层：米开朗琪罗与十九世纪收藏',
      elevation: 0,
      stackOrder: 0,
      outline: [
        [-7, -5],
        [7, -5],
        [7, 5],
        [1, 5],
        [1, 7],
        [-7, 7],
        [-7, -5],
      ],
      spaces: [
        space('colossus', '巨像厅', -4.8, 3.8, 3.4, 4.8, 'hall'),
        space('prisoners', '囚徒长廊', -1.2, 0.4, 2.4, 8.1, 'gallery'),
        space('david', '《大卫》圆厅', 1.3, -3.1, 2.5, 2.8, 'hall'),
        space('gipsoteca', '巴托里尼石膏馆', 4.6, 0, 3.6, 8.4, 'gallery'),
        space(
          'main-stair-ground',
          '上层楼梯与电梯',
          -5.6,
          -3.8,
          1.8,
          1.6,
          'circulation',
        ),
      ],
    },
    {
      id: 'upper',
      label: '上层：十三至十五世纪绘画',
      elevation: 3.1,
      stackOrder: 1,
      outline: [
        [-7, -5],
        [1, -5],
        [1, 5],
        [-7, 5],
        [-7, -5],
      ],
      spaces: [
        space('gold-ground', '金地绘画展区', -2.1, 0, 5.2, 8, 'gallery'),
        space(
          'main-stair-upper',
          '楼梯与电梯平台',
          -5.6,
          -3.8,
          1.8,
          1.6,
          'circulation',
        ),
      ],
    },
  ],
  openings: [
    {
      floorId: 'ground',
      kind: 'archway',
      position: [-3, 1.7],
      connects: ['colossus', 'prisoners'],
    },
    {
      floorId: 'ground',
      kind: 'archway',
      position: [0, -3.1],
      connects: ['prisoners', 'david'],
    },
    {
      floorId: 'ground',
      kind: 'archway',
      position: [2.8, 0],
      connects: ['david', 'gipsoteca'],
    },
  ],
  routeStops: [
    { floorId: 'ground', spaceId: 'colossus', position: [-4.8, 3.8] },
    { floorId: 'ground', spaceId: 'prisoners', position: [-1.2, 0.4] },
    { floorId: 'ground', spaceId: 'david', position: [1.3, -3.1] },
    { floorId: 'ground', spaceId: 'gipsoteca', position: [4.6, 0] },
    { floorId: 'upper', spaceId: 'gold-ground', position: [-2.1, 0] },
  ],
  sourceManifest: [
    {
      authority: 'official',
      scope: ['footprint', 'spaces', 'levels', 'route'],
      title: 'Galleria dell’Accademia Firenze 2026 visitor kit and floor map',
      url: 'https://www.galleriaaccademiafirenze.it/wp-content/uploads/2026/02/Galleria-Accademia-Fi-Kit-visita-ENG.pdf',
      verifiedAt: '2026-09-03',
    },
  ],
  verticalLinks: [
    {
      id: 'visitor-stair',
      kind: 'stairs',
      label: '上层访客楼梯',
      landings: [
        { floorId: 'ground', position: [-5.6, -3.8] },
        { floorId: 'upper', position: [-5.6, -3.8] },
      ],
    },
    {
      id: 'accessible-lift',
      kind: 'lift',
      label: '无障碍电梯',
      landings: [
        { floorId: 'ground', position: [-6.2, -3.8] },
        { floorId: 'upper', position: [-6.2, -3.8] },
      ],
    },
  ],
};

const mediciChapels: StackedFloorPlan = {
  mode: 'stacked-floorplan',
  floors: [
    {
      id: 'crypt',
      label: '地下层：墓穴、珍宝与洛林墓穴',
      elevation: -2.8,
      stackOrder: 0,
      outline: [
        [-6, -5],
        [6, -5],
        [6, 5],
        [-6, 5],
        [-6, -5],
      ],
      spaces: [
        space('medici-crypt', '梅第奇墓穴', -3.6, 0.8, 3.8, 6.7, 'chapel'),
        space('treasury', '圣洛伦佐珍宝', 0.3, 2.3, 3.3, 3.5, 'gallery'),
        space('lorraine-crypt', '洛林墓穴', 3.8, -0.5, 3.1, 7.4, 'chapel'),
        space(
          'crypt-circulation',
          '入口坡道与楼梯厅',
          0,
          -3.6,
          3.4,
          1.8,
          'circulation',
        ),
      ],
    },
    {
      id: 'monumental',
      label: '纪念层：王公礼拜堂与新圣器室',
      elevation: 0,
      stackOrder: 1,
      outline: [
        [-6, -5],
        [6, -5],
        [6, 5],
        [-6, 5],
        [-6, -5],
      ],
      spaces: [
        {
          id: 'princes-chapel',
          label: '王公礼拜堂',
          kind: 'chapel',
          polygon: [
            [-4.8, -3.2],
            [-1.5, -4.6],
            [1.5, -4.6],
            [4.8, -3.2],
            [4.8, 2.1],
            [1.5, 4.6],
            [-1.5, 4.6],
            [-4.8, 2.1],
            [-4.8, -3.2],
          ],
        },
        space(
          'new-sacristy',
          '米开朗琪罗新圣器室',
          4.4,
          3.5,
          2.4,
          2.2,
          'chapel',
        ),
        space(
          'monumental-landing',
          '楼梯与电梯平台',
          0,
          -3.5,
          2.1,
          1.5,
          'circulation',
        ),
      ],
    },
  ],
  openings: [
    {
      floorId: 'crypt',
      kind: 'archway',
      position: [-1.5, 1.7],
      connects: ['medici-crypt', 'treasury'],
    },
    {
      floorId: 'crypt',
      kind: 'archway',
      position: [2, 1],
      connects: ['treasury', 'lorraine-crypt'],
    },
    {
      floorId: 'monumental',
      kind: 'door',
      position: [4, 3.2],
      connects: ['princes-chapel', 'new-sacristy'],
    },
  ],
  routeStops: [
    { floorId: 'crypt', spaceId: 'medici-crypt', position: [-3.6, 0.8] },
    { floorId: 'crypt', spaceId: 'treasury', position: [0.3, 2.3] },
    { floorId: 'monumental', spaceId: 'princes-chapel', position: [0, 0] },
    { floorId: 'monumental', spaceId: 'new-sacristy', position: [4.4, 3.5] },
    { floorId: 'crypt', spaceId: 'lorraine-crypt', position: [3.8, -0.5] },
  ],
  sourceManifest: [
    {
      authority: 'official',
      scope: ['spaces', 'levels', 'route'],
      title: 'Musei del Bargello: Medici Chapels museum guide',
      url: 'https://bargellomusei.it/en/museum/cappelle-medicee/',
      verifiedAt: '2026-09-03',
    },
    {
      authority: 'official',
      scope: ['levels', 'route'],
      title:
        'FeelFlorence: Medici Chapels visitor and accessibility information',
      url: 'https://www.feelflorence.it/en/points-interest/museum-medici-chapels',
      verifiedAt: '2026-09-03',
    },
  ],
  verticalLinks: [
    {
      id: 'crypt-monumental-stair',
      kind: 'stairs',
      label: '墓穴至王公礼拜堂楼梯',
      landings: [
        { floorId: 'crypt', position: [0, -3.6] },
        { floorId: 'monumental', position: [0, -3.5] },
      ],
    },
    {
      id: 'museum-lift',
      kind: 'lift',
      label: '博物馆电梯及新圣器室平台升降机',
      landings: [
        { floorId: 'crypt', position: [1, -3.6] },
        { floorId: 'monumental', position: [1, -3.5] },
      ],
    },
  ],
};

const vasariCorridor: StackedFloorPlan = {
  mode: 'stacked-floorplan',
  floors: [
    {
      id: 'corridor',
      label: '乌菲兹D19至波波里花园的高架走廊',
      elevation: 0,
      stackOrder: 0,
      outline: [
        [-12, -2],
        [-8, -2],
        [-8, -1],
        [-2, -1],
        [-2, -3],
        [3, -3],
        [3, -1],
        [8, -1],
        [8, 1],
        [12, 1],
        [12, 3],
        [7, 3],
        [7, 1],
        [2, 1],
        [2, -1],
        [-1, -1],
        [-1, 1],
        [-9, 1],
        [-9, 2],
        [-12, 2],
        [-12, -2],
      ],
      spaces: [
        space('d19', '乌菲兹一层D19集合点', -10.5, 0, 2.4, 3.2, 'hall'),
        space('uffizi-link', '乌菲兹连接段', -5.2, 0, 5.8, 1.5, 'circulation'),
        space(
          'ponte-vecchio',
          '老桥上层连续窗带',
          0.5,
          -2,
          4.2,
          1.4,
          'circulation',
        ),
        space(
          'mannelli-felicita',
          '曼内利塔与圣费利奇塔绕行段',
          5.2,
          0,
          4.2,
          1.5,
          'circulation',
        ),
        space(
          'boboli-exit',
          '波波里出口与阿曼纳蒂庭院',
          10,
          2,
          3.2,
          1.4,
          'outdoor',
        ),
      ],
    },
  ],
  openings: [
    {
      floorId: 'corridor',
      kind: 'door',
      position: [-9, 0],
      connects: ['d19', 'uffizi-link'],
    },
    {
      floorId: 'corridor',
      kind: 'door',
      position: [8, 2],
      connects: ['mannelli-felicita', 'boboli-exit'],
    },
  ],
  routeStops: [
    { floorId: 'corridor', spaceId: 'd19', position: [-10.5, 0] },
    { floorId: 'corridor', spaceId: 'uffizi-link', position: [-5.2, 0] },
    { floorId: 'corridor', spaceId: 'ponte-vecchio', position: [0.5, -2] },
    { floorId: 'corridor', spaceId: 'mannelli-felicita', position: [5.2, 0] },
    { floorId: 'corridor', spaceId: 'boboli-exit', position: [10, 2] },
  ],
  sourceManifest: [
    {
      authority: 'official',
      scope: ['footprint', 'spaces', 'route'],
      title:
        'Uffizi Galleries: Vasari Corridor official route map and regulations',
      url: 'https://pdf.uffizi.it/1777908455903-mappa-e-regolamento_4.pdf',
      verifiedAt: '2026-09-03',
    },
  ],
  verticalLinks: [],
};

const pitti: StackedFloorPlan = {
  mode: 'stacked-floorplan',
  floors: [
    {
      id: 'ground',
      label: '地面层：庭院与大公珍宝馆',
      elevation: 0,
      stackOrder: 0,
      outline: [
        [-9, -5],
        [9, -5],
        [9, 5],
        [-9, 5],
        [-9, -5],
      ],
      spaces: [
        space('ammannati-court', '阿曼纳蒂庭院', 0, 0, 6.5, 6, 'courtyard'),
        space('treasury', '大公珍宝馆', -6.3, 0, 4, 8.2, 'gallery'),
        space(
          'ground-circulation',
          '入口、寄存与楼梯厅',
          6.4,
          0,
          3.8,
          8.2,
          'circulation',
        ),
      ],
    },
    {
      id: 'piano-nobile',
      label: '一层：帕拉蒂纳画廊与皇家公寓',
      elevation: 3.2,
      stackOrder: 1,
      outline: [
        [-9, -5],
        [9, -5],
        [9, 5],
        [-9, 5],
        [-9, -5],
      ],
      spaces: [
        space('palatine', '帕拉蒂纳画廊与行星厅', -4.2, 0, 7.5, 8.2, 'gallery'),
        space(
          'royal-apartments',
          '皇家公寓入口与房间组',
          4.2,
          0,
          7.5,
          8.2,
          'gallery',
        ),
        space(
          'piano-landing',
          '主楼梯与电梯厅',
          0,
          -3.9,
          2.4,
          1.3,
          'circulation',
        ),
      ],
    },
    {
      id: 'second',
      label: '二层：现代艺术馆与服饰馆',
      elevation: 6.4,
      stackOrder: 2,
      outline: [
        [-9, -5],
        [9, -5],
        [9, 5],
        [-9, 5],
        [-9, -5],
      ],
      spaces: [
        space('modern-art', '现代艺术馆', -3.8, 0, 8.2, 8.2, 'gallery'),
        space('costume', '服饰馆参观分支', 5.2, 0, 5, 8.2, 'gallery'),
        space(
          'second-landing',
          '楼梯与电梯厅',
          0,
          -3.9,
          2.4,
          1.3,
          'circulation',
        ),
      ],
    },
  ],
  openings: [
    {
      floorId: 'ground',
      kind: 'archway',
      position: [-3.3, 0],
      connects: ['ammannati-court', 'treasury'],
    },
    {
      floorId: 'piano-nobile',
      kind: 'door',
      position: [0, 0],
      connects: ['palatine', 'royal-apartments'],
    },
    {
      floorId: 'second',
      kind: 'door',
      position: [0.3, 0],
      connects: ['modern-art', 'costume'],
    },
  ],
  routeStops: [
    { floorId: 'ground', spaceId: 'ammannati-court', position: [0, 0] },
    { floorId: 'piano-nobile', spaceId: 'palatine', position: [-4.2, 0] },
    {
      floorId: 'piano-nobile',
      spaceId: 'royal-apartments',
      position: [4.2, 0],
    },
    { floorId: 'second', spaceId: 'modern-art', position: [-3.8, 0] },
    { floorId: 'second', spaceId: 'costume', position: [5.2, 0] },
  ],
  sourceManifest: [
    {
      authority: 'official',
      scope: ['spaces', 'levels'],
      title: 'Uffizi Galleries: Pitti Palace collections by floor',
      url: 'https://www.uffizi.it/en/pitti-palace',
      verifiedAt: '2026-09-03',
    },
    {
      authority: 'official',
      scope: ['footprint', 'spaces', 'route'],
      title: 'Uffizi Galleries: official Pitti Palace floor-plan guide sample',
      url: 'https://shop.uffizi.it/wp-content/uploads/2022/04/9788833400075-PITTIeng_assaggio.pdf',
      verifiedAt: '2026-09-03',
    },
  ],
  verticalLinks: [
    {
      id: 'palace-stair',
      kind: 'stairs',
      label: '宫殿主楼梯',
      landings: [
        { floorId: 'ground', position: [6.4, -3.2] },
        { floorId: 'piano-nobile', position: [0, -3.9] },
        { floorId: 'second', position: [0, -3.9] },
      ],
    },
    {
      id: 'visitor-lift',
      kind: 'lift',
      label: '访客电梯',
      landings: [
        { floorId: 'ground', position: [7.1, -3.2] },
        { floorId: 'piano-nobile', position: [0.8, -3.9] },
        { floorId: 'second', position: [0.8, -3.9] },
      ],
    },
  ],
};

const towerRing: PlanPoint[] = [
  [0, -4],
  [2.8, -2.8],
  [4, 0],
  [2.8, 2.8],
  [0, 4],
  [-2.8, 2.8],
  [-4, 0],
  [-2.8, -2.8],
  [0, -4],
];

const leaningTower: StackedFloorPlan = {
  mode: 'stacked-floorplan',
  floors: [
    {
      id: 'base',
      label: '基座与底层柱廊',
      elevation: 0,
      stackOrder: 0,
      outline: towerRing,
      spaces: [
        space('base-entry', '入口基座与浮雕', 0, 2.7, 2.4, 1.4, 'circulation'),
        {
          id: 'exterior-loggia',
          label: '底层外部柱廊',
          kind: 'outdoor',
          polygon: [
            [-2.5, -1.8],
            [0, -3.3],
            [2.5, -1.8],
            [2.5, 1.8],
            [0, 3.3],
            [-2.5, 1.8],
            [-2.5, -1.8],
          ],
        },
      ],
    },
    {
      id: 'spiral',
      label: '内部螺旋登塔段',
      elevation: 3,
      stackOrder: 1,
      outline: towerRing,
      spaces: [
        {
          id: 'spiral-stair',
          label: '内部螺旋梯',
          kind: 'circulation',
          polygon: [
            [-2.8, -2.1],
            [0, -3.2],
            [2.8, -2.1],
            [2.8, 2.1],
            [0, 3.2],
            [-2.8, 2.1],
            [-2.8, -2.1],
          ],
        },
      ],
    },
    {
      id: 'belfry',
      label: '钟层',
      elevation: 6,
      stackOrder: 2,
      outline: towerRing,
      spaces: [
        {
          id: 'seven-bells',
          label: '七口钟与开敞钟廊',
          kind: 'hall',
          polygon: [
            [-2.8, -2.1],
            [0, -3.2],
            [2.8, -2.1],
            [2.8, 2.1],
            [0, 3.2],
            [-2.8, 2.1],
            [-2.8, -2.1],
          ],
        },
      ],
    },
    {
      id: 'summit',
      label: '顶部环台',
      elevation: 8.5,
      stackOrder: 3,
      outline: towerRing,
      spaces: [space('top-ring', '顶部环形观景台', 0, 0, 5.4, 5.4, 'outdoor')],
    },
  ],
  openings: [
    {
      floorId: 'base',
      kind: 'gate',
      position: [0, 3.5],
      connects: ['base-entry', 'exterior-loggia'],
    },
  ],
  routeStops: [
    { floorId: 'base', spaceId: 'base-entry', position: [0, 2.7] },
    { floorId: 'base', spaceId: 'exterior-loggia', position: [-2.2, 0] },
    { floorId: 'spiral', spaceId: 'spiral-stair', position: [0, 0] },
    { floorId: 'belfry', spaceId: 'seven-bells', position: [0, 0] },
    { floorId: 'summit', spaceId: 'top-ring', position: [0, 0] },
  ],
  sourceManifest: [
    {
      authority: 'official',
      scope: ['footprint'],
      title: 'Opera della Primaziale Pisana: Square of Miracles map',
      url: 'https://www.opapisa.it/en/mappa/',
      verifiedAt: '2026-09-03',
    },
    {
      authority: 'official',
      scope: ['spaces', 'levels', 'route'],
      title: 'Opera della Primaziale Pisana: Leaning Tower guide',
      url: 'https://www.opapisa.it/en/square-of-miracles/tower/',
      verifiedAt: '2026-09-03',
    },
  ],
  verticalLinks: [
    {
      id: 'marble-spiral',
      kind: 'stairs',
      label: '内部石砌螺旋梯',
      landings: [
        { floorId: 'base', position: [0, 0] },
        { floorId: 'spiral', position: [0, 0] },
        { floorId: 'belfry', position: [0, 0] },
        { floorId: 'summit', position: [0, 0] },
      ],
    },
  ],
};

const pisaCathedral: StackedFloorPlan = {
  mode: 'stacked-floorplan',
  floors: [
    {
      id: 'cathedral',
      label: '主教座堂礼拜层',
      elevation: 0,
      stackOrder: 0,
      outline: [
        [-4, -8],
        [4, -8],
        [4, -3],
        [7, -3],
        [7, 3],
        [4, 3],
        [4, 8],
        [-4, 8],
        [-4, 3],
        [-7, 3],
        [-7, -3],
        [-4, -3],
        [-4, -8],
      ],
      spaces: [
        space('west-facade', '西立面多层柱廊', 0, 7, 6.8, 1.5, 'outdoor'),
        space('nave', '五廊式中央中殿', 0, 1.8, 6.6, 8, 'hall'),
        space('pulpit', '乔瓦尼·皮萨诺讲坛', -2.5, -1.8, 2.2, 2.2, 'hall'),
        space('apse', '后殿马赛克', 0, -6.5, 6.5, 2, 'chapel'),
        space(
          'san-ranieri-door',
          '圣拉涅利门',
          5.9,
          0,
          1.7,
          4.5,
          'circulation',
        ),
      ],
    },
  ],
  openings: [
    {
      floorId: 'cathedral',
      kind: 'gate',
      position: [0, 7.8],
      connects: ['west-facade', 'nave'],
    },
    {
      floorId: 'cathedral',
      kind: 'gate',
      position: [6.8, 0],
      connects: ['san-ranieri-door'],
    },
  ],
  routeStops: [
    { floorId: 'cathedral', spaceId: 'west-facade', position: [0, 7] },
    { floorId: 'cathedral', spaceId: 'nave', position: [0, 1.8] },
    { floorId: 'cathedral', spaceId: 'pulpit', position: [-2.5, -1.8] },
    { floorId: 'cathedral', spaceId: 'apse', position: [0, -6.5] },
    { floorId: 'cathedral', spaceId: 'san-ranieri-door', position: [5.9, 0] },
  ],
  sourceManifest: [
    {
      authority: 'official',
      scope: ['footprint'],
      title: 'Opera della Primaziale Pisana: Square of Miracles map',
      url: 'https://www.opapisa.it/en/mappa/',
      verifiedAt: '2026-09-03',
    },
    {
      authority: 'official',
      scope: ['spaces', 'route'],
      title: 'Opera della Primaziale Pisana: Cathedral guide',
      url: 'https://www.opapisa.it/en/square-of-miracles/cathedral/',
      verifiedAt: '2026-09-03',
    },
  ],
  verticalLinks: [],
};

const baptisteryRing: PlanPoint[] = [
  [0, -5],
  [2.5, -4.3],
  [4.3, -2.5],
  [5, 0],
  [4.3, 2.5],
  [2.5, 4.3],
  [0, 5],
  [-2.5, 4.3],
  [-4.3, 2.5],
  [-5, 0],
  [-4.3, -2.5],
  [-2.5, -4.3],
  [0, -5],
];

const pisaBaptistery: StackedFloorPlan = {
  mode: 'stacked-floorplan',
  floors: [
    {
      id: 'ground',
      label: '地面层：同心圆礼拜空间',
      elevation: 0,
      stackOrder: 0,
      outline: baptisteryRing,
      spaces: [
        {
          id: 'exterior-loggia',
          label: '外部罗曼式与哥特式柱廊',
          kind: 'outdoor',
          polygon: [
            [-1.6, 3.1],
            [0, 4.55],
            [1.6, 3.1],
            [1.15, 2.75],
            [-1.15, 2.75],
            [-1.6, 3.1],
          ],
        },
        {
          id: 'font',
          label: '八角洗礼池',
          kind: 'chapel',
          polygon: [
            [0, -1.6],
            [1.15, -1.15],
            [1.6, 0],
            [1.15, 1.15],
            [0, 1.6],
            [-1.15, 1.15],
            [-1.6, 0],
            [-1.15, -1.15],
            [0, -1.6],
          ],
        },
        space('pulpit', '尼古拉·皮萨诺讲坛', 2.7, -0.8, 1.6, 1.8, 'hall'),
        space(
          'spiral-ground',
          '女性廊螺旋梯入口',
          -2.8,
          0,
          1.4,
          2.2,
          'circulation',
        ),
      ],
    },
    {
      id: 'gallery',
      label: '女性廊层',
      elevation: 3.3,
      stackOrder: 1,
      outline: baptisteryRing,
      spaces: [
        {
          id: 'womens-gallery',
          label: '女性廊与穹顶俯瞰',
          kind: 'gallery',
          polygon: [
            [0, -4.1],
            [2.05, -3.5],
            [3.5, -2.05],
            [4.1, 0],
            [3.5, 2.05],
            [2.05, 3.5],
            [0, 4.1],
            [-2.05, 3.5],
            [-3.5, 2.05],
            [-4.1, 0],
            [-3.5, -2.05],
            [-2.05, -3.5],
            [0, -4.1],
          ],
        },
        space(
          'spiral-gallery',
          '螺旋梯上层出口',
          -2.8,
          0,
          1.4,
          2.2,
          'circulation',
        ),
      ],
    },
  ],
  openings: [
    {
      floorId: 'ground',
      kind: 'gate',
      position: [0, 4.8],
      connects: ['exterior-loggia'],
    },
  ],
  routeStops: [
    { floorId: 'ground', spaceId: 'exterior-loggia', position: [0, 3.9] },
    { floorId: 'ground', spaceId: 'font', position: [0, 0] },
    { floorId: 'ground', spaceId: 'pulpit', position: [2.7, -0.8] },
    { floorId: 'gallery', spaceId: 'womens-gallery', position: [0, 0] },
  ],
  sourceManifest: [
    {
      authority: 'official',
      scope: ['footprint'],
      title: 'Opera della Primaziale Pisana: Square of Miracles map',
      url: 'https://www.opapisa.it/en/mappa/',
      verifiedAt: '2026-09-03',
    },
    {
      authority: 'official',
      scope: ['spaces', 'levels', 'route'],
      title: 'Opera della Primaziale Pisana: Baptistery guide',
      url: 'https://www.opapisa.it/en/square-of-miracles/baptistery/',
      verifiedAt: '2026-09-03',
    },
  ],
  verticalLinks: [
    {
      id: 'gallery-spiral',
      kind: 'stairs',
      label: '女性廊螺旋梯',
      landings: [
        { floorId: 'ground', position: [-2.8, 0] },
        { floorId: 'gallery', position: [-2.8, 0] },
      ],
    },
  ],
};

const camposanto: StackedFloorPlan = {
  mode: 'stacked-floorplan',
  floors: [
    {
      id: 'cloister',
      label: '纪念墓园回廊层',
      elevation: 0,
      stackOrder: 0,
      outline: [
        [-10, -5],
        [10, -5],
        [10, 5],
        [-10, 5],
        [-10, -5],
      ],
      spaces: [
        space('central-court', '中央露天墓地', 0, 0, 13.8, 5, 'courtyard'),
        space(
          'north-fresco',
          '北侧生命与死亡壁画回廊',
          0,
          -4,
          17.8,
          1.5,
          'gallery',
        ),
        space(
          'south-sarcophagi',
          '南侧石棺与罗马铭文回廊',
          0,
          4,
          17.8,
          1.5,
          'gallery',
        ),
        space(
          'east-monuments',
          '东侧地方纪念碑回廊',
          8.8,
          0,
          1.5,
          6.6,
          'gallery',
        ),
        space('west-entry', '西侧入口回廊', -8.8, 0, 1.5, 6.6, 'circulation'),
      ],
    },
  ],
  openings: [
    {
      floorId: 'cloister',
      kind: 'gate',
      position: [-9.8, 0],
      connects: ['west-entry'],
    },
    {
      floorId: 'cloister',
      kind: 'archway',
      position: [0, -2.8],
      connects: ['central-court', 'north-fresco'],
    },
  ],
  routeStops: [
    { floorId: 'cloister', spaceId: 'central-court', position: [0, 0] },
    { floorId: 'cloister', spaceId: 'north-fresco', position: [0, -4] },
    { floorId: 'cloister', spaceId: 'south-sarcophagi', position: [0, 4] },
    { floorId: 'cloister', spaceId: 'east-monuments', position: [8.8, 0] },
  ],
  sourceManifest: [
    {
      authority: 'official',
      scope: ['footprint'],
      title: 'Opera della Primaziale Pisana: Square of Miracles map',
      url: 'https://www.opapisa.it/en/mappa/',
      verifiedAt: '2026-09-03',
    },
    {
      authority: 'official',
      scope: ['spaces', 'route'],
      title: 'Opera della Primaziale Pisana: Camposanto guide',
      url: 'https://www.opapisa.it/en/square-of-miracles/camposanto/',
      verifiedAt: '2026-09-03',
    },
  ],
  verticalLinks: [],
};

const operaPisa: StackedFloorPlan = {
  mode: 'stacked-floorplan',
  floors: [
    {
      id: 'ground',
      label: '地面层：建筑雕塑与庭院',
      elevation: 0,
      stackOrder: 0,
      outline: [
        [-8, -5],
        [8, -5],
        [8, 5],
        [-8, 5],
        [-8, -5],
      ],
      spaces: [
        space(
          'cathedral-baptistery',
          '大教堂与洗礼堂雕塑区',
          -5.3,
          1.8,
          4.2,
          5.4,
          'gallery',
        ),
        space(
          'giovanni-pisano',
          '乔瓦尼·皮萨诺专题区',
          -0.9,
          1.8,
          3.8,
          5.4,
          'gallery',
        ),
        space('tower-elements', '斜塔构件区', 3.2, 1.8, 3.6, 5.4, 'gallery'),
        space(
          'cloister',
          '庭院回廊与洗礼堂巨像',
          5.8,
          -2.2,
          3.2,
          3.6,
          'courtyard',
        ),
        space(
          'ground-landing',
          '访客楼梯与电梯',
          -5.8,
          -3.7,
          2.2,
          1.5,
          'circulation',
        ),
      ],
    },
    {
      id: 'upper',
      label: '上层：礼仪收藏与观景廊',
      elevation: 3.2,
      stackOrder: 1,
      outline: [
        [-8, -5],
        [8, -5],
        [8, 5],
        [-8, 5],
        [-8, -5],
      ],
      spaces: [
        space(
          'liturgical',
          '亨利七世墓葬物、织物与礼仪收藏',
          -1,
          0.8,
          11,
          6.6,
          'gallery',
        ),
        space('upper-loggia', '上层观景廊', 6.3, 0.8, 2.4, 6.6, 'outdoor'),
        space(
          'upper-landing',
          '访客楼梯与电梯',
          -5.8,
          -3.7,
          2.2,
          1.5,
          'circulation',
        ),
      ],
    },
  ],
  openings: [
    {
      floorId: 'ground',
      kind: 'archway',
      position: [-3.1, 1.8],
      connects: ['cathedral-baptistery', 'giovanni-pisano'],
    },
    {
      floorId: 'ground',
      kind: 'archway',
      position: [1.1, 1.8],
      connects: ['giovanni-pisano', 'tower-elements'],
    },
    {
      floorId: 'upper',
      kind: 'archway',
      position: [5.1, 0.8],
      connects: ['liturgical', 'upper-loggia'],
    },
  ],
  routeStops: [
    {
      floorId: 'ground',
      spaceId: 'cathedral-baptistery',
      position: [-5.3, 1.8],
    },
    { floorId: 'ground', spaceId: 'giovanni-pisano', position: [-0.9, 1.8] },
    { floorId: 'ground', spaceId: 'tower-elements', position: [3.2, 1.8] },
    { floorId: 'upper', spaceId: 'liturgical', position: [-1, 0.8] },
    { floorId: 'ground', spaceId: 'cloister', position: [5.8, -2.2] },
  ],
  sourceManifest: [
    {
      authority: 'official',
      scope: ['spaces', 'levels', 'route'],
      title: 'Opera della Primaziale Pisana: Opera del Duomo Museum guide',
      url: 'https://www.opapisa.it/en/square-of-miracles/opera-del-duomo-museum/',
      verifiedAt: '2026-09-03',
    },
    {
      authority: 'official',
      scope: ['levels', 'route'],
      title:
        'Opera della Primaziale Pisana: accessibility and visitor services',
      url: 'https://www.opapisa.it/wp-content/uploads/2024/06/VASupport-and-welcoming-services-available-for-visitors-with-reduced-mobility.pdf',
      verifiedAt: '2026-09-03',
    },
  ],
  verticalLinks: [
    {
      id: 'museum-stair',
      kind: 'stairs',
      label: '博物馆主楼梯',
      landings: [
        { floorId: 'ground', position: [-5.8, -3.7] },
        { floorId: 'upper', position: [-5.8, -3.7] },
      ],
    },
    {
      id: 'visitor-lift',
      kind: 'lift',
      label: '访客电梯',
      landings: [
        { floorId: 'ground', position: [-6.5, -3.7] },
        { floorId: 'upper', position: [-6.5, -3.7] },
      ],
    },
  ],
};

const pantheonRing: PlanPoint[] = [
  [0, -6],
  [3, -5.2],
  [5.2, -3],
  [6, 0],
  [5.2, 3],
  [3, 5.2],
  [0, 6],
  [-3, 5.2],
  [-5.2, 3],
  [-6, 0],
  [-5.2, -3],
  [-3, -5.2],
  [0, -6],
];

const pantheon: StackedFloorPlan = {
  mode: 'stacked-floorplan',
  floors: [
    {
      id: 'rotunda',
      label: '门廊与圆厅礼拜层',
      elevation: 0,
      stackOrder: 0,
      outline: [
        [-6, -10],
        [6, -10],
        [6, -5],
        [5.2, -3],
        [6, 0],
        [5.2, 3],
        [3, 5.2],
        [0, 6],
        [-3, 5.2],
        [-5.2, 3],
        [-6, 0],
        [-5.2, -3],
        [-6, -5],
        [-6, -10],
      ],
      spaces: [
        space(
          'piazza-front',
          '广场正面与阿格里帕铭文',
          0,
          -9,
          10.5,
          1.4,
          'outdoor',
        ),
        space('portico', '花岗岩柱门廊与青铜门', 0, -6.9, 10.5, 2.2, 'hall'),
        {
          id: 'rotunda-centre',
          label: '圆厅中心与穹顶天窗',
          kind: 'hall',
          polygon: pantheonRing,
        },
        space('raphael-tomb', '拉斐尔墓与侧龛', 4.35, 1.4, 1.2, 1.4, 'chapel'),
        space('high-altar', '主祭坛与离场方向', 0, 4.7, 2.2, 1, 'chapel'),
      ],
    },
  ],
  openings: [
    {
      floorId: 'rotunda',
      kind: 'gate',
      position: [0, -5.8],
      connects: ['portico', 'rotunda-centre'],
    },
  ],
  routeStops: [
    { floorId: 'rotunda', spaceId: 'piazza-front', position: [0, -9] },
    { floorId: 'rotunda', spaceId: 'portico', position: [0, -6.9] },
    { floorId: 'rotunda', spaceId: 'rotunda-centre', position: [0, 0] },
    { floorId: 'rotunda', spaceId: 'raphael-tomb', position: [4.5, 1.4] },
    { floorId: 'rotunda', spaceId: 'high-altar', position: [0, 4.7] },
  ],
  sourceManifest: [
    {
      authority: 'official',
      scope: ['footprint', 'spaces', 'route'],
      title:
        'Direzione Musei Nazionali Roma: Pantheon guide and interactive map',
      url: 'https://direzionemuseiroma.cultura.gov.it/en/pantheon/',
      verifiedAt: '2026-09-03',
    },
    {
      authority: 'official',
      scope: ['footprint', 'spaces'],
      title: 'Direzione Musei Nazionali Roma: Pantheon historical background',
      url: 'https://direzionemuseiroma.cultura.gov.it/en/pantheon/historical-background/',
      verifiedAt: '2026-09-03',
    },
  ],
  verticalLinks: [],
};

const borghese: StackedFloorPlan = {
  mode: 'stacked-floorplan',
  floors: [
    {
      id: 'ground',
      label: '地面层：雕塑与古物展室',
      elevation: 0,
      stackOrder: 0,
      outline: [
        [-8, -5],
        [8, -5],
        [8, 5],
        [-8, 5],
        [-8, -5],
      ],
      spaces: [
        space(
          'ticket-cloakroom',
          '票务与寄存区',
          -6.2,
          3.5,
          2.6,
          2.1,
          'service',
        ),
        space('room-3', '3室：阿波罗与达芙妮', -3.4, 0, 3.2, 3.4, 'gallery'),
        space('room-4', '4室：劫夺普洛塞庇娜', 0.2, 0, 3.2, 3.4, 'gallery'),
        space('room-8', '8室：卡拉瓦乔群', 4, 0, 3.6, 3.4, 'gallery'),
        space('exit', '地面层出口', 6.3, 3.5, 2.5, 2.1, 'circulation'),
        space(
          'ground-landing',
          '主楼梯与电梯',
          0,
          -3.7,
          2.4,
          1.5,
          'circulation',
        ),
      ],
    },
    {
      id: 'upper',
      label: '上层：绘画展室',
      elevation: 3.1,
      stackOrder: 1,
      outline: [
        [-8, -5],
        [8, -5],
        [8, 5],
        [-8, 5],
        [-8, -5],
      ],
      spaces: [
        space(
          'painting-galleries',
          '拉斐尔、提香等上层绘画室',
          0,
          0,
          13.5,
          7.5,
          'gallery',
        ),
        space(
          'upper-landing',
          '主楼梯与电梯',
          0,
          -3.7,
          2.4,
          1.5,
          'circulation',
        ),
      ],
    },
  ],
  openings: [
    {
      floorId: 'ground',
      kind: 'door',
      position: [-4.9, 0],
      connects: ['ticket-cloakroom', 'room-3'],
    },
    {
      floorId: 'ground',
      kind: 'door',
      position: [-1.6, 0],
      connects: ['room-3', 'room-4'],
    },
    {
      floorId: 'ground',
      kind: 'door',
      position: [2.1, 0],
      connects: ['room-4', 'room-8'],
    },
    {
      floorId: 'ground',
      kind: 'door',
      position: [5.8, 1.8],
      connects: ['room-8', 'exit'],
    },
  ],
  routeStops: [
    { floorId: 'ground', spaceId: 'ticket-cloakroom', position: [-6.2, 3.5] },
    { floorId: 'ground', spaceId: 'room-3', position: [-3.4, 0] },
    { floorId: 'ground', spaceId: 'room-4', position: [0.2, 0] },
    { floorId: 'ground', spaceId: 'room-8', position: [4, 0] },
    { floorId: 'upper', spaceId: 'painting-galleries', position: [0, 0] },
    { floorId: 'ground', spaceId: 'exit', position: [6.3, 3.5] },
  ],
  sourceManifest: [
    {
      authority: 'official',
      scope: ['spaces', 'levels'],
      title: 'Galleria Borghese: official museum and room information',
      url: 'https://galleriaborghese.cultura.gov.it/en/il-museo/la-villa/',
      verifiedAt: '2026-09-03',
    },
    {
      authority: 'official',
      scope: ['footprint', 'spaces', 'levels', 'route'],
      title: 'Galleria Borghese: official numbered floor plan',
      url: 'https://galleriaborghese.cultura.gov.it/en/wp-content/uploads/BirdCage_CS_04-05_ENG_Press-R.pdf',
      verifiedAt: '2026-09-03',
    },
  ],
  verticalLinks: [
    {
      id: 'main-stair',
      kind: 'stairs',
      label: '别墅主楼梯',
      landings: [
        { floorId: 'ground', position: [0, -3.7] },
        { floorId: 'upper', position: [0, -3.7] },
      ],
    },
    {
      id: 'visitor-lift',
      kind: 'lift',
      label: '访客电梯',
      landings: [
        { floorId: 'ground', position: [0.8, -3.7] },
        { floorId: 'upper', position: [0.8, -3.7] },
      ],
    },
  ],
};

const colosseumEllipse: PlanPoint[] = [
  [0, -8],
  [6, -6.7],
  [10, -4],
  [12, 0],
  [10, 4],
  [6, 6.7],
  [0, 8],
  [-6, 6.7],
  [-10, 4],
  [-12, 0],
  [-10, -4],
  [-6, -6.7],
  [0, -8],
];

const colosseum: StackedFloorPlan = {
  mode: 'stacked-floorplan',
  floors: [
    {
      id: 'underground',
      label: '地下层：后台走廊与升降系统',
      elevation: -3,
      stackOrder: 0,
      outline: colosseumEllipse,
      spaces: [
        space(
          'underground-corridor',
          '地下层中央与侧向走廊',
          0,
          0,
          14,
          3,
          'circulation',
        ),
        space('lift-shafts', '升降井与活门遗迹', 4.8, 2.6, 5, 2.4, 'gallery'),
        space(
          'underground-stair',
          '地下层访客楼梯',
          -7.8,
          -2.8,
          2.4,
          2.2,
          'circulation',
        ),
      ],
    },
    {
      id: 'arena',
      label: '竞技场与入口层',
      elevation: 0,
      stackOrder: 1,
      outline: colosseumEllipse,
      spaces: [
        {
          id: 'external-arches',
          label: '外立面与编号拱门',
          kind: 'outdoor',
          polygon: [
            [-4.8, -5.9],
            [0, -7.4],
            [4.8, -5.9],
            [3.7, -5.1],
            [0, -6.2],
            [-3.7, -5.1],
            [-4.8, -5.9],
          ],
        },
        space(
          'security-entry',
          '实名票安检入口',
          -7.5,
          -3.5,
          1.8,
          1.2,
          'service',
        ),
        space('arena-floor', '竞技场面', 0, 0, 13.5, 5.3, 'hall'),
        space(
          'arena-stair',
          '竞技场与地下层楼梯',
          -7.8,
          -2.8,
          2.4,
          2.2,
          'circulation',
        ),
      ],
    },
    {
      id: 'cavea',
      label: '观众席视角层',
      elevation: 3.2,
      stackOrder: 2,
      outline: colosseumEllipse,
      spaces: [
        {
          id: 'spectator-view',
          label: '观众席与环廊视角',
          kind: 'outdoor',
          polygon: [
            [0, -7],
            [5.5, -5.8],
            [9, -3.4],
            [10.5, 0],
            [9, 3.4],
            [5.5, 5.8],
            [0, 7],
            [-5.5, 5.8],
            [-9, 3.4],
            [-10.5, 0],
            [-9, -3.4],
            [-5.5, -5.8],
            [0, -7],
          ],
        },
        space(
          'cavea-stair',
          '观众席上行楼梯',
          7.7,
          -3.2,
          2.4,
          2.2,
          'circulation',
        ),
      ],
    },
  ],
  openings: [
    {
      floorId: 'arena',
      kind: 'gate',
      position: [-6.4, -4.2],
      connects: ['external-arches', 'security-entry'],
    },
    {
      floorId: 'arena',
      kind: 'gate',
      position: [-5.8, -2.5],
      connects: ['security-entry', 'arena-floor'],
    },
  ],
  routeStops: [
    { floorId: 'arena', spaceId: 'external-arches', position: [0, -6.6] },
    { floorId: 'arena', spaceId: 'security-entry', position: [-7.5, -3.5] },
    {
      floorId: 'underground',
      spaceId: 'underground-corridor',
      position: [0, 0],
    },
    { floorId: 'underground', spaceId: 'lift-shafts', position: [4.8, 2.6] },
    { floorId: 'arena', spaceId: 'arena-floor', position: [0, 0] },
    { floorId: 'cavea', spaceId: 'spectator-view', position: [0, 5.5] },
  ],
  sourceManifest: [
    {
      authority: 'official',
      scope: ['footprint', 'spaces', 'levels', 'route'],
      title: 'Parco archeologico del Colosseo: MyColosseum interactive guide',
      url: 'https://colosseo.it/en/my-colosseum-app/',
      verifiedAt: '2026-09-03',
    },
    {
      authority: 'official',
      scope: ['spaces', 'levels', 'route'],
      title:
        'Parco archeologico del Colosseo: Full Experience Underground and Arena',
      url: 'https://colosseo.it/en/tickets/full-experience-underground-arena/',
      verifiedAt: '2026-09-03',
    },
  ],
  verticalLinks: [
    {
      id: 'underground-route',
      kind: 'stairs',
      label: '导览员带领的地下层楼梯',
      landings: [
        { floorId: 'arena', position: [-7.8, -2.8] },
        { floorId: 'underground', position: [-7.8, -2.8] },
      ],
    },
    {
      id: 'cavea-route',
      kind: 'stairs',
      label: '竞技场至观众席楼梯',
      landings: [
        { floorId: 'arena', position: [7.7, -3.2] },
        { floorId: 'cavea', position: [7.7, -3.2] },
      ],
    },
  ],
};

const vaticanPost: StackedFloorPlan = {
  mode: 'stacked-floorplan',
  floors: [
    {
      id: 'kiosk',
      label: '圣彼得广场左半圆邮政办事点',
      elevation: 0,
      stackOrder: 0,
      outline: [
        [-5, -3],
        [5, -3],
        [5, 3],
        [-5, 3],
        [-5, -3],
      ],
      spaces: [
        space(
          'colonnade-approach',
          '左半圆柱廊外部识别点',
          -3.8,
          0,
          2,
          4.8,
          'outdoor',
        ),
        space('stamp-counter', '邮票与集邮柜台', -0.8, 0.9, 3, 1.8, 'service'),
        space('writing-place', '地址填写位置', 2.2, 1, 2.2, 1.7, 'service'),
        space('post-counter', '盖戳柜台或投递口', 1, -1.4, 4.5, 1.5, 'service'),
      ],
    },
  ],
  openings: [
    {
      floorId: 'kiosk',
      kind: 'gate',
      position: [-2.8, 0],
      connects: ['colonnade-approach', 'stamp-counter'],
    },
  ],
  routeStops: [
    { floorId: 'kiosk', spaceId: 'colonnade-approach', position: [-3.8, 0] },
    { floorId: 'kiosk', spaceId: 'stamp-counter', position: [-0.8, 0.9] },
    { floorId: 'kiosk', spaceId: 'writing-place', position: [2.2, 1] },
    { floorId: 'kiosk', spaceId: 'post-counter', position: [1, -1.4] },
  ],
  sourceManifest: [
    {
      authority: 'official',
      scope: ['spaces', 'route'],
      title: 'Poste Vaticane: postal services useful information',
      url: 'https://postevaticane.va/en/the-service/postal-services/useful-information',
      verifiedAt: '2026-09-03',
    },
    {
      authority: 'official',
      scope: ['footprint', 'spaces'],
      title: 'Vatican City State: new post office for St Peter’s Square',
      url: 'https://www.vaticanstate.va/it/novita/1212-un-nuovo-ufficio-postale-per-piazza-san-pietro.html',
      verifiedAt: '2026-09-03',
    },
  ],
  verticalLinks: [],
};

export const tuscanyRomeFloorPlans: Record<string, StackedFloorPlan> = {
  'florence-duomo': florenceDuomo,
  'accademia-florence': accademiaFlorence,
  'vasari-corridor': vasariCorridor,
  pitti,
  'leaning-tower': leaningTower,
  'pisa-cathedral': pisaCathedral,
  'pisa-baptistery': pisaBaptistery,
  camposanto,
  pantheon,
  borghese,
  colosseum,
  'vatican-post': vaticanPost,
};

const sourceLimitedInventory: Record<string, FloorPlanInventoryEntry> = {
  'medici-chapels': {
    status: 'source-limited',
    note: '官方资料确认墓穴、王公礼拜堂、新圣器室和垂直顺序，但未发布覆盖整个游客区域的统一平面；局部学术测绘不足以可靠拼接完整室内拓扑，因此不展示推测模型。',
    sources: mediciChapels.sourceManifest,
  },
  'opera-pisa': {
    status: 'source-limited',
    note: '官网确认两层藏品分区和游客动线，但未发布可核验的完整建筑外轮廓与展厅平面，因此不把矩形展区当作真实室内地图。',
    sources: operaPisa.sourceManifest,
  },
  'giunti-odeon': {
    status: 'source-limited',
    note: '官网确认门厅、观众厅书店、舞台银幕、楼座与一楼镜厅，但未发布可核验的完整平面和楼层连接关系，因此不生成室内结构。',
    sources: [
      {
        authority: 'official',
        scope: ['spaces', 'levels'],
        title: 'Giunti Odeon official location guide',
        url: 'https://www.giuntiodeon.com/en/location',
        verifiedAt: '2026-09-03',
      },
    ],
  },
  sinopie: {
    status: 'source-limited',
    note: '官网确认藏品分组与存在访客电梯，但没有发布展厅轮廓、楼层分配或可核验参观连接关系，因此不按作品清单臆造房间。',
    sources: [
      {
        authority: 'official',
        scope: ['spaces'],
        title: 'Opera della Primaziale Pisana: Sinopie Museum guide',
        url: 'https://www.opapisa.it/en/square-of-miracles/sinopie-museum/',
        verifiedAt: '2026-09-03',
      },
      {
        authority: 'official',
        scope: ['levels'],
        title:
          'Opera della Primaziale Pisana: accessibility and visitor services',
        url: 'https://www.opapisa.it/wp-content/uploads/2024/06/VASupport-and-welcoming-services-available-for-visitors-with-reduced-mobility.pdf',
        verifiedAt: '2026-09-03',
      },
    ],
  },
  'mercato-centrale': {
    status: 'source-limited',
    note: '官方资料只确认地面传统市场与上层餐饮空间，未发布可核验的摊位平面、垂直连接或固定参观路线，保留外部/节点导览。',
    sources: [
      {
        authority: 'official',
        scope: ['spaces', 'levels'],
        title: 'Mercato Centrale Firenze: how the two public levels work',
        url: 'https://www.mercatocentrale.com/florence/how-it-works/',
        verifiedAt: '2026-09-03',
      },
    ],
  },
};

export const tuscanyRomeInventory: Record<string, FloorPlanInventoryEntry> = {
  ...Object.fromEntries(
    Object.entries(tuscanyRomeFloorPlans).map(([slug, floorPlan]) => [
      slug,
      {
        status: 'ready' as const,
        note: '已按官网或权威平面与参观资料建立显式分层拓扑，节点顺序与现有 guide stops 完全一致。',
        sources: floorPlan.sourceManifest,
      },
    ]),
  ),
  ...sourceLimitedInventory,
};
